### ISSUE TITLE
慕名而来：关于8KB的问题！

### ISSUE THREAD

**Issue by CodingOX** [mrsWangxing/netty-ssl-send-large-file#1]
都是中国人，我就说中午拉，我目前也想用netty来做大文件传输，我发现你提供的demo确实会导致原始文件和当前文件字节数不匹配的问题！
我看到你在 https://github.com/netty/netty/issues/6202 提到了修改了写的方式就ok了？
能否告知这种写的方式是什么?
还有相关的文件传输经验是否有可以分享的?
谢谢！

**Comment by mrsWangxing** [comment]
时间过了好久了，具体我也忘记了，建议您忘记这段代码，重新找下别的demo，我不是在这个基础上改的，原来是同事找的别的代码例子，解决了这个问题。



    
    
        
            
                
                    
                        
                    
                    
                        
                            1435648802
                            
                            
                                
                                    邮箱：1435648802@qq.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


            在2018年09月09日 18:14，CodingNew 写道： 都是中国人，我就说中午拉，我目前也想用netty来做大文件传输，我发现你提供的demo确实会导致原始文件和当前文件字节数不匹配的问题！
我看到你在 netty/netty#6202 提到了修改了写的方式就ok了？
能否告知这种写的方式是什么?
还有相关的文件传输经验是否有可以分享的?
谢谢！

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mrsWangxing/netty-ssl-send-large-file","title":"mrsWangxing/netty-ssl-send-large-file","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mrsWangxing/netty-ssl-send-large-file"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"慕名而来：关于8KB的问题！ (#1)"}],"action":{"name":"View Issue","url":"https://github.com/mrsWangxing/netty-ssl-send-large-file/issues/1"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mrsWangxing/netty-ssl-send-large-file/issues/1",
"url": "https://github.com/mrsWangxing/netty-ssl-send-large-file/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "慕名而来：关于8KB的问题！ (#1)",
"sections": [
{
"text": "",
"activityTitle": "**CodingNew**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@CodingOX",
"facts": [
{
"name": "Repository: ",
"value": "mrsWangxing/netty-ssl-send-large-file"
},
{
"name": "Issue #: ",
"value": 1
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"mrsWangxing/netty-ssl-send-large-file\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"mrsWangxing/netty-ssl-send-large-file\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/mrsWangxing/netty-ssl-send-large-file/issues/1"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 377546533\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by CodingOX** [comment]
非常谢谢你的回复！
